### PR TITLE
Revert "Push build to Maven repositiory"

### PR DESCRIPTION
**Pull request by svenwltr**
Reverts rebuy-de/consul-java-client#4

It does nothing ...

### CODE REVIEW

**Comment by svenwltr** [comment]
@rebuy-de/it-platform

**Comment by bjoernhaeuser** [comment]
:+1:

**Comment by ghost** [comment]
:+1: the goggles

**Comment by florian-zeidler** [comment]
@svenwltr Then we should set up a issue in Jenkins-Jobs, shouldn't we?

**Comment by svenwltr** [comment]
No. I wanted it to push the release to Maven. Not the master branch.

**Comment by florian-zeidler** [comment]
@svenwltr We could still provide a template for that. Make releases in Jenkins, sounds kinda cool.

**Comment by svenwltr** [comment]
I like that idea. However, then we have to make sure, that we don't accidentally overwrite an existing version on Maven (for example when somebody forgot to adjust the version).

/cc @bjoernhaeuser

**Comment by florian-zeidler** [comment]
It would always create the next one, you just have to take care of major ones.

**Pull request merged**
